# Define Firmware Version Number
export PRJ_VERSION = 0x00000041

# Define target output
target: bit

# Define target part
export PRJ_PART = XC7Z030SBG485-1

export USE_XVC_DEBUG=0

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
