#!/usr/bin/env python3

import pyrogue

pyrogue.addLibraryPath('../../firmware/submodules/rce-gen3-fw-lib/python')
pyrogue.addLibraryPath('../../firmware/submodules/surf/python')
pyrogue.addLibraryPath('../../firmware/python')
pyrogue.addLibraryPath('../python')

import pyrogue.pydm
import pyrogue.gui
import rogue
import logging

# All 5 md
host = ["192.168.1.102"]

from ucsc_hn import RateTestRoot

with RateTestRoot(host=host) as root:

    pyrogue.pydm.runPyDM(root=root)


