#!/usr/bin/env python3

import pyrogue
import pyrogue.pydm
import ucsc_hn
import argparse

# Set the argument parser
parser = argparse.ArgumentParser('UCSC H&N Pet Control')

parser.add_argument(
    "--emulate",
    action   = 'store_true',
    required = False,
    default  = False,
    help     = "Emulate operation without hardware.",
)

parser.add_argument(
    "--host",
    action   = 'append',
    required = True,
    help     = "Host ID, multiple allowed.",
)

# Get the arguments
args = parser.parse_args()

with ucsc_hn.MultiRenaRoot(host=args.host,pollEn=True,emulate=args.emulate) as root:
    ui = os.path.dirname(ucsc_hn.__file__) + '/GuiTop.py'
    pyrogue.pydm.runPyDM(root=root,ui=ui)
