#!/usr/bin/env python3

import pyrogue
import pyrogue.pydm
import sys
import ucsc_hn

if len(sys.argv) == 1:
    print("Usage: renaGui host1 [host2 [host3 ...]]")
    exit(1)

with ucsc_hn.MultiRenaRoot(host=sys.argv[1:],pollEn=True) as root:
    ui = os.path.dirname(ucsc_hn.__file__) + '/GuiTop.py'
    pyrogue.pydm.runPyDM(root=root,ui=ui)


