#!/usr/bin/env python3

import argparse
import os
import sys
import pyrogue
import pyrogue.pydm

# Set the argument parser
parser = argparse.ArgumentParser('UCSC H&N Pet Control')

parser.add_argument(
    "--emulate",
    action   = 'store_true',
    required = False,
    default  = False,
    help     = "Emulate operation without hardware.",
)

parser.add_argument(
    "--local",
    action   = 'store_true',
    required = False,
    default  = False,
    help     = "Use local python libraries (git checkout)."
)

parser.add_argument(
    "--host",
    action   = 'append',
    required = False,
    help     = "Host ID, multiple allowed.",
)

# Get the arguments
args = parser.parse_args()

if args.local:
    pyrogue.addLibraryPath('../../firmware/submodules/rce-gen3-fw-lib/python')
    pyrogue.addLibraryPath('../../firmware/submodules/surf/python')
    pyrogue.addLibraryPath('../../firmware/python')
    pyrogue.addLibraryPath('../python')

if args.host is None:
    if args.emulate:
        host = [f"192.168.2.{x}" for x in range(100,110)]
    else:
        parser.print_help()
        sys.exit(1)
else:
    host = args.host

import ucsc_hn

with ucsc_hn.MultiRenaRoot(host=host,pollEn=True,emulate=args.emulate) as root:
    #print(f"System has {root.nodeCount} nodes")

    ui = os.path.dirname(ucsc_hn.__file__) + '/GuiTop.py'
    pyrogue.pydm.runPyDM(serverList=root.zmqServer.address,ui=ui)

