#!/usr/bin/env python3

import pyrogue

pyrogue.addLibraryPath('../../firmware/submodules/rce-gen3-fw-lib/python')
pyrogue.addLibraryPath('../../firmware/submodules/surf/python')
pyrogue.addLibraryPath('../../firmware/python')
pyrogue.addLibraryPath('../python')

import pyrogue.pydm
import pyrogue.gui
import rogue
import logging
import ucsc_hn
import os


# Master only
#host = ["192.168.2.100"]

# master and slave
#host = ["192.168.2.100","192.168.2.101", "192.168.2.103"]

# All 4
#host = ["192.168.2.100","192.168.2.101","192.168.2.103","192.168.2.104"]
#host = ["192.168.2.100","192.168.2.101","192.168.2.210","192.168.2.104"]

# All 5
#host = ["192.168.2.100","192.168.2.101","192.168.2.210","192.168.2.103","192.168.2.104"]



# All 5 md
#host = ["192.168.2.100","192.168.2.103","192.168.2.104","192.168.2.101","192.168.2.210"]

host = ["192.168.2.100", "192.168.2.101","192.168.2.105","192.168.2.103","192.168.2.104","192.168.2.110","192.168.2.111","192.168.2.112","192.168.2.113","192.168.2.114"]

#rogue.Logging.setFilter('pyrogue.memory.block.InterCardRoot.PcieControl[0].Fpga.PrbsTx',rogue.Logging.Debug)
#rogue.Logging.setFilter('pyrogue.memory.block',rogue.Logging.Debug)

#rogue.Logging.setLevel(rogue.Logging.Debug)

#logger = logging.getLogger('pyrogue.PollQueue')
#logger.setLevel(logging.DEBUG)

with ucsc_hn.MultiRenaRoot(host=host,pollEn=True) as root:
    ui = os.path.dirname(ucsc_hn.__file__) + '/GuiTop.py'
    pyrogue.pydm.runPyDM(root=root,ui=ui)

